/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana10;

/**
 *
 * @author F4_di
 */
public class frmInteresGanado extends javax.swing.JFrame {

    /**
     * Creates new form frmInteresGanado
     */
    public frmInteresGanado() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiCapital = new javax.swing.JLabel();
        etiTotal = new javax.swing.JLabel();
        etiInteres = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtCapital = new javax.swing.JTextField();
        txtInteres = new javax.swing.JTextField();
        etiImagen = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        etiImagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Cálculo de Interés ganado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiCapital.setText("Capital Invertido: ");
        jPanel1.add(etiCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, -1));

        etiTotal.setText("Total en el Banco:");
        jPanel1.add(etiTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, -1));

        etiInteres.setText("Interés ganado:");
        jPanel1.add(etiInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, -1));

        txtTotal.setEditable(false);
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, -1));
        jPanel1.add(txtCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, -1));

        txtInteres.setEditable(false);
        jPanel1.add(txtInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, -1));

        etiImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semana10/chanchito.png"))); // NOI18N
        jPanel1.add(etiImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 70, -1));

        btnCalcular.setBackground(new java.awt.Color(153, 153, 153));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 130, -1));

        etiImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semana10/chanchito.png"))); // NOI18N
        jPanel1.add(etiImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //Declaracion e inicializacion de variables
        double capital=0.0; //declara e inicializa en 0 la variable capital
        double interes=0.0; //declara e inicializa en 0 la variable interes
        double total=0.0; // declara e inicializa en 0 la variable total
        //Lectura de datos de entrada
        //Captura la Informacion de la caja de texto capital y se la asigna a 
        //la variable capital convertida en double
        capital=Double.parseDouble(txtCapital.getText());
        //Procesos
        interes=capital*0.02;
        total=capital+interes;
        //Salida de resultados
        txtInteres.setText(String.valueOf(interes));
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInteresGanado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInteresGanado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInteresGanado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInteresGanado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInteresGanado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel etiCapital;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiImagen1;
    private javax.swing.JLabel etiInteres;
    private javax.swing.JLabel etiTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
