/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana10;

/**
 *
 * @author F4_di
 */
public class frmInverciondeDiseño extends javax.swing.JFrame {

    /**
     * Creates new form frmInverciondeDiseño
     */
    public frmInverciondeDiseño() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiPrecioCompra = new javax.swing.JLabel();
        etiGanancia = new javax.swing.JLabel();
        txtMonto3 = new javax.swing.JTextField();
        etiImagen = new javax.swing.JLabel();
        etiPrecioVenta = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular1 = new javax.swing.JButton();
        etiPrecioCompra1 = new javax.swing.JLabel();
        etiPrecioCompra2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtMonto2 = new javax.swing.JTextField();
        txtMonto1 = new javax.swing.JTextField();
        txtPorc1 = new javax.swing.JTextField();
        txtPorc2 = new javax.swing.JTextField();
        etiPrecioVenta1 = new javax.swing.JLabel();
        txtPorc3 = new javax.swing.JTextField();
        etiImagen2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Ganancia Articulo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiPrecioCompra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiPrecioCompra.setText("Porcentaje");
        etiPrecioCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 80, -1));

        etiGanancia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiGanancia.setText("Inversionista 2");
        etiGanancia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));
        jPanel1.add(txtMonto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, -1));

        etiImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semana10/inversion.png"))); // NOI18N
        jPanel1.add(etiImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, 80));

        etiPrecioVenta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiPrecioVenta.setText("Monto total de la Inversión:");
        jPanel1.add(etiPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, -1));

        btnLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 120, -1));

        btnCalcular1.setBackground(new java.awt.Color(153, 153, 153));
        btnCalcular1.setText("Calcular");
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, -1));

        etiPrecioCompra1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiPrecioCompra1.setText("Inversionista 1");
        etiPrecioCompra1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiPrecioCompra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        etiPrecioCompra2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiPrecioCompra2.setText("Monto de dinero");
        etiPrecioCompra2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiPrecioCompra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, -1));

        txtTotal.setEditable(false);
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 170, -1));
        jPanel1.add(txtMonto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, -1));
        jPanel1.add(txtMonto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 120, -1));

        txtPorc1.setEditable(false);
        jPanel1.add(txtPorc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 120, -1));

        txtPorc2.setEditable(false);
        jPanel1.add(txtPorc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, -1));

        etiPrecioVenta1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiPrecioVenta1.setText("Inversionista 3");
        jPanel1.add(etiPrecioVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        txtPorc3.setEditable(false);
        jPanel1.add(txtPorc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, -1));

        etiImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semana10/inversion.png"))); // NOI18N
        jPanel1.add(etiImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtMonto1.setText("");
        txtMonto2.setText("");
        txtMonto3.setText("");
        
        txtPorc1.setText("");
        txtPorc2.setText("");
        txtPorc3.setText("");
        
        txtTotal.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        // TODO add your handling code here:
        double monto1=0, monto2=0, monto3=0, total=0;
        double porc1=0, porc2=0, porc3=0;
        
        monto1=Double.parseDouble(txtMonto1.getText());
        monto2=Double.parseDouble(txtMonto2.getText());
        monto3=Double.parseDouble(txtMonto3.getText());
        
        total=monto1+monto2+monto3;
        
        porc1=monto1*100/total;
        porc2=monto2*100/total;
        porc3=monto3*100/total;
        
        txtTotal.setText(String.valueOf(total));
        txtPorc1.setText(String.valueOf(Math.rint(porc1)));
        txtPorc2.setText(String.valueOf(Math.rint(porc2)));
        txtPorc3.setText(String.valueOf(Math.rint(porc3)));
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInverciondeDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInverciondeDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInverciondeDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInverciondeDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInverciondeDiseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel etiGanancia;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiImagen2;
    private javax.swing.JLabel etiPrecioCompra;
    private javax.swing.JLabel etiPrecioCompra1;
    private javax.swing.JLabel etiPrecioCompra2;
    private javax.swing.JLabel etiPrecioVenta;
    private javax.swing.JLabel etiPrecioVenta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMonto1;
    private javax.swing.JTextField txtMonto2;
    private javax.swing.JTextField txtMonto3;
    private javax.swing.JTextField txtPorc1;
    private javax.swing.JTextField txtPorc2;
    private javax.swing.JTextField txtPorc3;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
