/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana10;

/**
 *
 * @author F4_di
 */
public class frmPresupuestoHospital extends javax.swing.JFrame {

    /**
     * Creates new form frmPresupuestoHospital
     */
    public frmPresupuestoHospital() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiPresupuesto = new javax.swing.JLabel();
        etiGinecologia = new javax.swing.JLabel();
        txtPresupuesto = new javax.swing.JTextField();
        txtGinecologia = new javax.swing.JTextField();
        etiImagen = new javax.swing.JLabel();
        etiPediatria = new javax.swing.JLabel();
        etiTraumatologia = new javax.swing.JLabel();
        txtPediatria = new javax.swing.JTextField();
        txtTraumatologia = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        etiImagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Presupuesto Hospital", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiPresupuesto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiPresupuesto.setText("Monto del presupuesto: ");
        etiPresupuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, -1));

        etiGinecologia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiGinecologia.setText("Ginecologia 40%: ");
        etiGinecologia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(etiGinecologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, -1));
        jPanel1.add(txtPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 140, -1));

        txtGinecologia.setEditable(false);
        jPanel1.add(txtGinecologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 140, -1));

        etiImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semana10/Hospital.png"))); // NOI18N
        jPanel1.add(etiImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 80));

        etiPediatria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiPediatria.setText("Pedatria 25%: ");
        jPanel1.add(etiPediatria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 130, -1));

        etiTraumatologia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiTraumatologia.setText("Traumatologia 35%: ");
        jPanel1.add(etiTraumatologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        txtPediatria.setEditable(false);
        jPanel1.add(txtPediatria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 140, -1));

        txtTraumatologia.setEditable(false);
        jPanel1.add(txtTraumatologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 140, -1));

        btnCalcular.setBackground(new java.awt.Color(153, 153, 153));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 180, -1));

        etiImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semana10/Hospital.png"))); // NOI18N
        jPanel1.add(etiImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double presupuesto=0, ginecologia=0, pediatria=0, traumatologia=0;
        presupuesto=Double.parseDouble(txtPresupuesto.getText());
        ginecologia=presupuesto*0.40;
        pediatria=presupuesto*0.25;
        traumatologia=presupuesto*0.35;
        txtGinecologia.setText(String.valueOf(ginecologia));
        txtPediatria.setText(String.valueOf(pediatria));
        txtTraumatologia.setText(String.valueOf(traumatologia));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPresupuestoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPresupuestoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPresupuestoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPresupuestoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPresupuestoHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel etiGinecologia;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiImagen1;
    private javax.swing.JLabel etiPediatria;
    private javax.swing.JLabel etiPresupuesto;
    private javax.swing.JLabel etiTraumatologia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGinecologia;
    private javax.swing.JTextField txtPediatria;
    private javax.swing.JTextField txtPresupuesto;
    private javax.swing.JTextField txtTraumatologia;
    // End of variables declaration//GEN-END:variables
}
