/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana10;

/**
 *
 * @author F4_di
 */
public class frmTipoJubilacion extends javax.swing.JFrame {

    /**
     * Creates new form frmTipoJubilacion
     */
    public frmTipoJubilacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etiGanancia = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtAntiguedad = new javax.swing.JTextField();
        etiGanancia1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        etiGanancia2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Tipo de Jubilación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 120, -1));

        btnProcesar.setBackground(new java.awt.Color(153, 153, 153));
        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 120, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de entrada"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiGanancia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiGanancia.setText("Edad:");
        etiGanancia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(etiGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 130, 20));
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 106, -1));
        jPanel2.add(txtAntiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 106, -1));

        etiGanancia1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiGanancia1.setText("Años laborados(antguedad):");
        etiGanancia1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(etiGanancia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de salida"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiGanancia2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        etiGanancia2.setText("Tipo de Jubilacion:");
        etiGanancia2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(etiGanancia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 115, 20));

        txtTipo.setEditable(false);
        jPanel3.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, 270, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 310, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAntiguedad.setText("");
        txtEdad.setText("");
        txtTipo.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        int edad=0, antiguedad=0;
        edad=Integer.parseInt(txtEdad.getText());
        antiguedad=Integer.parseInt(txtAntiguedad.getText());
        if((edad>=60)&&(antiguedad<25))
            txtTipo.setText("La jubilación es por:EDAD.");
        else if((edad>=60)&& (antiguedad>25))
                txtTipo.setText("La jubilación es por:EDAD ADULTA.");
        else if((edad<60)&&(antiguedad>25))
            txtTipo.setText("La jubilación es por:ANTUGÜEDAD JOVÉN.");
        else
            txtTipo.setText("No tiene derecho a jubilarse");
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoJubilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoJubilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoJubilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoJubilacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoJubilacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel etiGanancia;
    private javax.swing.JLabel etiGanancia1;
    private javax.swing.JLabel etiGanancia2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAntiguedad;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
